---
#
# 
# Author: Gabriel Torres – gabriel.torres@oracle.com  
# Purpose: Disable Firewall in Linux machines 
#         
# Copyright (c) 2017, 2019, Oracle and/or its affiliates. All rights reserved.
#


# Linux 6 firewall service
- name: Stop Firewall Linux 6 
  become: yes
  service:
   name: iptables
   state: stopped
   enabled: False

- name: Disable Firewall Linux 6 
  become: yes
  service:
   name: ip6tables
   state: stopped
   enabled: False
