---
#
# 
# Author: Gabriel Torres – gabriel.torres@oracle.com  
# Purpose: Disable Firewall in Linux machines 
#         
# Copyright (c) 2017, 2019, Oracle and/or its affiliates. All rights reserved.
#

- name: Stop Firewall Linux 7
  become: yes
  systemd: 
    name: firewalld 
    state: stopped
 
- name: Disable Firewall Linux 7
  become: yes
  systemd:
    name: firewalld
    enabled: no
  


